/**
 * Full column contract of "NEW - Brand mapping files Template.xlsx" (Template sheet).
 * 228 attributes in template order, grouped by cluster. Every transformed
 * sample row shown in the portal carries ALL of these columns — columns the
 * mapping engine could not fill stay empty so reviewers see the complete
 * Stibo attribute assignment at a glance.
 */

export interface TemplateColumn {
  /** Human attribute name, e.g. "Country" */
  name: string;
  /** Stibo attribute id, e.g. "AT_Country" — empty when #N/A in template */
  id: string;
  /** validation type: lov | text | number | regexp | date | legacyisodatetime */
  validation: string;
  /** template cluster: Basic | Commercial | Price | Cost | MC | Hierarchy | Online | Image (Online) | ... */
  cluster: string;
}

export const TEMPLATE_COLUMNS: TemplateColumn[] = [
  { name: "Country", id: "AT_Country", validation: "lov", cluster: "Basic" },
  { name: "Company", id: "AT_CompanyCode", validation: "lov", cluster: "Basic" },
  { name: "SBU", id: "AT_SBU", validation: "lov", cluster: "Basic" },
  { name: "Brand", id: "AT_Brand", validation: "lov", cluster: "Basic" },
  { name: "Brand Group", id: "AT_BrandGroup", validation: "lov", cluster: "Basic" },
  { name: "Brand Type", id: "AT_BrandType", validation: "lov", cluster: "Commercial" },
  { name: "Brand Category", id: "AT_BrandCategory", validation: "lov", cluster: "Commercial" },
  { name: "Brand Status", id: "AT_BrandStatus", validation: "lov", cluster: "Commercial" },
  { name: "BY Indicator", id: "AT_BYIndicator", validation: "lov", cluster: "System indicator" },
  { name: "SAP Indicator", id: "AT_SAPIndicator", validation: "lov", cluster: "System indicator" },
  { name: "Ecom Indicator", id: "AT_EcomIndicator", validation: "lov", cluster: "System indicator" },
  { name: "Principal Style Code", id: "AT_PrincipalStyleCode", validation: "text", cluster: "Basic" },
  { name: "Principal Style Description", id: "AT_PrincipalStyleDescription", validation: "text", cluster: "Basic" },
  { name: "Principal Color Code", id: "AT_PrincipalColorCode", validation: "text", cluster: "Basic" },
  { name: "Principal Color Description", id: "AT_PrincipalColorName", validation: "text", cluster: "Basic" },
  { name: "Principal Gender Code", id: "AT_PrincipalGenderCode", validation: "text", cluster: "Basic" },
  { name: "Principal Gender Description", id: "AT_PrincipalGenderDescription", validation: "text", cluster: "Basic" },
  { name: "Principal Age Code", id: "AT_PrincipalAgeCode", validation: "text", cluster: "Basic" },
  { name: "Principal Age Description", id: "AT_PrincipalAgeDescription", validation: "text", cluster: "Basic" },
  { name: "Principal Size", id: "AT_PrincipalSize", validation: "text", cluster: "Basic" },
  { name: "SAP Style Code", id: "AT_SAPStyleCode", validation: "text", cluster: "Basic" },
  { name: "Generic", id: "AT_Generic", validation: "text", cluster: "Basic" },
  { name: "Generic Description", id: "AT_GenericDescription", validation: "regexp", cluster: "Basic" },
  { name: "Variant", id: "AT_Variant", validation: "text", cluster: "Basic" },
  { name: "Variant Description", id: "AT_VariantDescription", validation: "text", cluster: "Basic" },
  { name: "SAP Color", id: "AT_Color", validation: "lov", cluster: "Basic" },
  { name: "SAP Size", id: "AT_Size", validation: "lov", cluster: "Basic" },
  { name: "Created on", id: "AT_Createdon", validation: "legacyisodatetime", cluster: "Basic" },
  { name: "Created by", id: "AT_Createdby", validation: "text", cluster: "Basic" },
  { name: "Musical Box Article Code", id: "AT_MusicalBoxArticleCode", validation: "text", cluster: "Basic" },
  { name: "MB Style code", id: "AT_MBStyleCode", validation: "text", cluster: "Basic" },
  { name: "MB Assortment Code", id: "AT_MBAssortmentCode", validation: "lov", cluster: "Basic" },
  { name: "Musical Box Article Description", id: "AT_MusicalBoxArticleDescription", validation: "text", cluster: "Basic" },
  { name: "Musical Box Components Qty", id: "AT_MusicalBoxComponentsQty", validation: "lov", cluster: "Basic" },
  { name: "Musical Box UOM", id: "AT_MusicalBoxUOM", validation: "lov", cluster: "Basic" },
  { name: "SAP Age", id: "AT_SAPAge", validation: "lov", cluster: "Basic" },
  { name: "SAP Gender", id: "AT_Gender", validation: "lov", cluster: "Basic" },
  { name: "Season", id: "AT_Season", validation: "lov", cluster: "Basic" },
  { name: "Season Year", id: "AT_SeasonYear", validation: "number", cluster: "Basic" },
  { name: "Country of Origin", id: "AT_CountryOrigin", validation: "lov", cluster: "Basic" },
  { name: "Vendor", id: "AT_Vendor", validation: "lov", cluster: "Basic" },
  { name: "Main Vendor Identification", id: "AT_MainVendorIdentification", validation: "text", cluster: "Basic" },
  { name: "Exchange Rate", id: "AT_ExchangeRate", validation: "number", cluster: "Price" },
  { name: "Pricing Distribution Channel", id: "AT_PricingDistributionChannel", validation: "lov", cluster: "Price" },
  { name: "Retail Price Currency", id: "AT_RetailPriceCurrency", validation: "lov", cluster: "Price" },
  { name: "Original Price", id: "AT_OriginalPrice", validation: "regexp", cluster: "Price" },
  { name: "Valid From", id: "", validation: "text", cluster: "Price" },
  { name: "Valid To", id: "", validation: "text", cluster: "Price" },
  { name: "Current price", id: "AT_CurrentPrice", validation: "regexp", cluster: "Price" },
  { name: "Discount Bucket", id: "AT_DiscountBucket", validation: "number", cluster: "Price" },
  { name: "Discount Bucket (Rounded)", id: "AT_DiscountBucketRounded", validation: "number", cluster: "Price" },
  { name: "Estimated Landed Cost", id: "AT_EstimatedLandedCost", validation: "number", cluster: "Cost" },
  { name: "FOB", id: "AT_FOB", validation: "regexp", cluster: "Cost" },
  { name: "FOB Currency", id: "AT_FOBCurrency", validation: "lov", cluster: "Cost" },
  { name: "Freight Cost", id: "AT_FreightCost", validation: "regexp", cluster: "Cost" },
  { name: "Royalty", id: "AT_Royalty", validation: "regexp", cluster: "Cost" },
  { name: "Royalty Deduction", id: "AT_RoyaltyDeduction", validation: "regexp", cluster: "Cost" },
  { name: "Commision", id: "", validation: "text", cluster: "Cost" },
  { name: "SGS", id: "AT_SGS", validation: "regexp", cluster: "Cost" },
  { name: "Marketing Fee", id: "AT_MarketingFee", validation: "regexp", cluster: "Cost" },
  { name: "Haddad Office Charge", id: "AT_HaddadOfficeCharge", validation: "regexp", cluster: "Cost" },
  { name: "Haddad Office Charge - Deduction", id: "AT_HaddadOfficeChargeDeduction", validation: "regexp", cluster: "Cost" },
  { name: "Safeguard Duty (ID Only)", id: "AT_SafeguardDutyIdOnly", validation: "number", cluster: "Cost" },
  { name: "Label Cost", id: "AT_LabelCost", validation: "regexp", cluster: "Cost" },
  { name: "Others", id: "AT_Others", validation: "number", cluster: "Cost" },
  { name: "MC Structure (Merchandise Category)", id: "", validation: "text", cluster: "MC" },
  { name: "SAP Product Division", id: "", validation: "text", cluster: "MC" },
  { name: "SAP Product Group", id: "", validation: "text", cluster: "MC" },
  { name: "SAP Product Category", id: "", validation: "text", cluster: "MC" },
  { name: "SAP Product Flag", id: "AT_SAPProductFlag", validation: "lov", cluster: "MC" },
  { name: "Principal Merchandise Hierarchy L1", id: "AT_PrincipalMerchandiseHierarchyL1", validation: "text", cluster: "Hierarchy" },
  { name: "Principal Merchandise Hierarchy L2", id: "AT_PrincipalMerchandiseHierarchyL2", validation: "text", cluster: "Hierarchy" },
  { name: "Principal Merchandise Hierarchy L3", id: "AT_PrincipalMerchandiseHierarchyL3", validation: "text", cluster: "Hierarchy" },
  { name: "Principal Merchandise Hierarchy L4", id: "AT_PrincipalMerchandiseHierarchyL4", validation: "text", cluster: "Hierarchy" },
  { name: "Principal Merchandise Hierarchy L5", id: "AT_PrincipalMerchandiseHierarchyL5", validation: "text", cluster: "Hierarchy" },
  { name: "Material Type", id: "AT_MaterialType", validation: "lov", cluster: "Commercial" },
  { name: "Article Category", id: "AT_SAPArticleCategory", validation: "lov", cluster: "Basic" },
  { name: "Internal Barcode", id: "AT_InternalBarcode", validation: "regexp", cluster: "Basic" },
  { name: "Principal Barcode", id: "AT_PrincipalBarcode", validation: "regexp", cluster: "Basic" },
  { name: "FG Barcode", id: "AT_FGBarcode", validation: "regexp", cluster: "Basic" },
  { name: "Main EAN Indicator", id: "AT_MainEANIndicator", validation: "lov", cluster: "Basic" },
  { name: "EAN Category", id: "AT_EANCategory", validation: "lov", cluster: "Basic" },
  { name: "Unit of Measurement (UoM)", id: "AT_UOM", validation: "lov", cluster: "Basic" },
  { name: "HS Code", id: "AT_HSCode", validation: "text", cluster: "Cost" },
  { name: "Nature of Article (NOA)", id: "", validation: "text", cluster: "Commercial" },
  { name: "Article Type", id: "", validation: "text", cluster: "Commercial" },
  { name: "Thumbnail Image", id: "", validation: "text", cluster: "Image (BY)" },
  { name: "BY Age", id: "AT_BYAge", validation: "lov", cluster: "Basic" },
  { name: "BY Gender", id: "AT_BYGender", validation: "lov", cluster: "Basic" },
  { name: "BCI", id: "AT_BCI", validation: "lov", cluster: "Image (BY)" },
  { name: "BY Color Group", id: "", validation: "text", cluster: "Basic" },
  { name: "BY Standardized Color", id: "", validation: "text", cluster: "Basic" },
  { name: "Price Range", id: "AT_PriceRange", validation: "lov", cluster: "Basic" },
  { name: "Silhouette", id: "AT_Silhouette", validation: "lov", cluster: "Basic" },
  { name: "Width", id: "AT_Width", validation: "lov", cluster: "Basic" },
  { name: "Material - Upper", id: "AT_MaterialUpper", validation: "lov", cluster: "Basic" },
  { name: "Fastening", id: "AT_Fastening", validation: "lov", cluster: "Basic" },
  { name: "Franchise", id: "", validation: "text", cluster: "Basic" },
  { name: "Content", id: "AT_Content", validation: "lov", cluster: "Basic" },
  { name: "Fabric", id: "AT_Fabric", validation: "lov", cluster: "Basic" },
  { name: "Pattern/Print", id: "AT_PatternPrint", validation: "lov", cluster: "Basic" },
  { name: "Fit", id: "AT_Fit", validation: "lov", cluster: "Basic" },
  { name: "Style", id: "AT_Style", validation: "lov", cluster: "Basic" },
  { name: "Material", id: "AT_Material", validation: "lov", cluster: "Basic" },
  { name: "Pack Details", id: "AT_PackDetails", validation: "lov", cluster: "Basic" },
  { name: "Style Type", id: "AT_StyleType", validation: "lov", cluster: "Basic" },
  { name: "Golf Club Flex", id: "AT_GolfClubFlex", validation: "lov", cluster: "Basic" },
  { name: "Golf Club Loft", id: "AT_GolfClubLoft", validation: "lov", cluster: "Basic" },
  { name: "Golf Club Length", id: "AT_GolfClubLength", validation: "lov", cluster: "Basic" },
  { name: "Heel Height", id: "AT_HeelHeight", validation: "lov", cluster: "Basic" },
  { name: "Heel Type", id: "AT_HeelType", validation: "lov", cluster: "Basic" },
  { name: "Occasion", id: "AT_Occasion", validation: "lov", cluster: "Basic" },
  { name: "Interest", id: "AT_Interest", validation: "lov", cluster: "Basic" },
  { name: "Sports Category EN", id: "AT_SportsCategoryEN", validation: "lov", cluster: "Translation (Online)" },
  { name: "Collection 1", id: "AT_Collection1", validation: "text", cluster: "Online" },
  { name: "Collection 2", id: "AT_Collection2", validation: "text", cluster: "Online" },
  { name: "Principal Color Description ID", id: "AT_ColorDescriptionID", validation: "text", cluster: "Translation (Online)" },
  { name: "Principal Color Description PH", id: "AT_ColorDescriptionPH", validation: "text", cluster: "Translation (Online)" },
  { name: "Principal Color Description MY", id: "AT_ColorDescriptionMY", validation: "text", cluster: "Translation (Online)" },
  { name: "Principal Color Description VN", id: "AT_ColorDescriptionVN", validation: "text", cluster: "Translation (Online)" },
  { name: "Principal Color Description TH", id: "AT_ColorDescriptionTH", validation: "text", cluster: "Translation (Online)" },
  { name: "Principal Color Description KH", id: "AT_ColorDescriptionKH", validation: "text", cluster: "Translation (Online)" },
  { name: "Country Size", id: "AT_CountrySize", validation: "lov", cluster: "Online" },
  { name: "E-com Size", id: "AT_EComSize", validation: "text", cluster: "Online" },
  { name: "E-com Ages Category", id: "AT_EComAgesCategory", validation: "lov", cluster: "Online" },
  { name: "Ecom Gender Description EN", id: "AT_EcomGenderDescriptionEN", validation: "text", cluster: "Online" },
  { name: "Ecom Product Name EN", id: "AT_EComProductNameEN", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name ID", id: "AT_EComProductNameID", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name PH", id: "AT_EComProductNamePH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name MY", id: "AT_EComProductNameMY", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name VN", id: "AT_EComProductNameVN", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name TH", id: "AT_EComProductNameTH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Product Name KH", id: "AT_EComProductNameKH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description EN", id: "AT_ShortDescriptionEN", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description ID", id: "AT_ShortDescriptionID", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description PH", id: "AT_ShortDescriptionPH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description MY", id: "AT_ShortDescriptionMY", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description VN", id: "AT_ShortDescriptionVN", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description TH", id: "AT_ShortDescriptionTH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Short Description KH", id: "AT_ShortDescriptionKH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long Description EN", id: "AT_LongDescriptionEN", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long Description ID", id: "AT_LongDescriptionID", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long Description PH", id: "AT_LongDescriptionPH", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long Description MY", id: "AT_LongDescriptionMY", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long DescriptionVN", id: "", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long DescriptionTH", id: "", validation: "text", cluster: "Translation (Online)" },
  { name: "Ecom Long Description KH", id: "AT_LongDescriptionKH", validation: "text", cluster: "Translation (Online)" },
  { name: "SPU Grouping", id: "AT_SPUGrouping", validation: "text", cluster: "Online" },
  { name: "SPU Grouping Name", id: "AT_SPUGroupingName", validation: "text", cluster: "Online" },
  { name: "Certificate No ( SNI , K3L , UTTP )", id: "", validation: "text", cluster: "Online" },
  { name: "Technology Used", id: "AT_TechnologyUsed", validation: "text", cluster: "Online" },
  { name: "Care Instruction EN", id: "AT_CareInstructionEN", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction ID", id: "AT_CareInstructionID", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction PH", id: "AT_CareInstructionPH", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction MY", id: "AT_CareInstructionMY", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction VN", id: "AT_CareInstructionVN", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction TH", id: "AT_CareInstructionTH", validation: "text", cluster: "Translation (Online)" },
  { name: "Care Instruction KH", id: "AT_CareInstructionKH", validation: "text", cluster: "Translation (Online)" },
  { name: "Launching Date", id: "AT_LaunchingDate", validation: "date", cluster: "Online" },
  { name: "Product Length X Width X Height ( in CM )", id: "", validation: "text", cluster: "Online" },
  { name: "Product Weight ( In Gram )", id: "", validation: "text", cluster: "Online" },
  { name: "Packaging Length ( in CM )", id: "", validation: "text", cluster: "Online" },
  { name: "Packaging Width ( in CM )", id: "", validation: "text", cluster: "Online" },
  { name: "Packaging Height ( in CM )", id: "", validation: "text", cluster: "Online" },
  { name: "Packaging Weight ( In Gram )", id: "", validation: "text", cluster: "Online" },
  { name: "Images Source", id: "AT_ImagesSource", validation: "lov", cluster: "Image (Online)" },
  { name: "Images 1", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 2", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 3", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 4", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 5", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 6", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 7", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 8", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 9", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 10", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 11", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 12", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 13", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 14", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 15", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 16", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 17", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 18", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 19", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 20", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 21", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 22", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 23", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 24", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 25", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 26", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 27", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 28", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 29", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 30", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 31", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 32", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 33", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 34", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 35", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 36", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 37", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 38", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 39", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 40", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 41", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 42", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 43", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 44", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 45", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 46", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 47", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 48", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 49", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "Images 50", id: "", validation: "text", cluster: "Image (Online)" },
  { name: "BY SBU", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "BY Brand", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "BY Division", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "BY Sub Division", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "BY Category", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "BY Sub Category", id: "", validation: "text", cluster: "Hierarchy" },
  { name: "Ecomm Concept", id: "AT_EcommConcept", validation: "lov", cluster: "Online" },
  { name: "Ecomm Sales Channel", id: "AT_EcommSalesChannel", validation: "lov", cluster: "Online" },
  { name: "Article Status", id: "AT_ArticleStatus", validation: "lov", cluster: "System indicator" },
  { name: "Incoming month", id: "AT_IncomingMonth", validation: "regexp", cluster: "Other" },
  { name: "Suggested Retail Price", id: "AT_SuggestedRetailPrice", validation: "number", cluster: "Price" },
  { name: "Proposed Retail Price", id: "AT_ProposedRetailPrice", validation: "number", cluster: "Price" },
];

/** Unique clusters in template order (for grouped table headers). */
export const TEMPLATE_CLUSTERS: string[] = Array.from(
  new Set(TEMPLATE_COLUMNS.map((c) => c.cluster))
);

/** id -> column index for fast row assembly. */
export const TEMPLATE_INDEX: Record<string, number> = TEMPLATE_COLUMNS.reduce(
  (acc, c, i) => {
    if (c.id) acc[c.id] = i;
    return acc;
  },
  {} as Record<string, number>
);

/** Expand a sparse mapped row {AT_X: v} into a dense array aligned to TEMPLATE_COLUMNS. */
export function denseRow(values: Record<string, string>): string[] {
  const dense = TEMPLATE_COLUMNS.map(() => "");
  for (const [k, v] of Object.entries(values)) {
    const idx = TEMPLATE_INDEX[k];
    if (idx !== undefined) dense[idx] = v ?? "";
  }
  return dense;
}
